name: Build

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: lint:output
      - uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_BACKEND }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      - uses: sonarsource/sonarqube-quality-gate-action@master
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_BACKEND }}
